### ISSUE TITLE
Create alias to support document types `csand` and `csa`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-csand#11]
Would this be a good idea? @opoudjis

**Comment by opoudjis** [comment]
Only if you renamed all the other gems, and that is (a) a lot of effort, (b) which makes the metanorma stack unstable (because that's what perpetual tinkering means), and (c) which doesn't impact any end consumers for brand recognition, because all they ever see for flavour branding is the `-t` argument in the metanorma-cli call.

Don't rename any gems. Just change the metanorma-cli options.

**Comment by ronaldtse** [comment]
True -- we can just change the "type" name used in the gem. We can provide aliases, e.g. `csand` and `csa` both point to the same processor.

**Comment by ronaldtse** [comment]
Updated title to reflect the request. We just need to update this line to provide both aliases:

https://github.com/metanorma/metanorma-csand/blob/60e9977ecb6a66102f6b4465b606608d00f7c017/lib/metanorma/csand/processor.rb#L8

**Comment by opoudjis** [comment]
—and update metanorma-cli

**Comment by opoudjis** [comment]
Implemented: `@short` can now take an array.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
